version: "3.6"

services:
  server:
    build: .
    volumes:
      - ./app:/app
    command: server
  client:
    build: .
    volumes:
      - ./app:/app
    command: client
    ports:
      - 5900
